library(ape)
library(vegan)
library(ecodist)

### mantel test between genetic and geographic distance
### genetic distance = parwise Fst 
### I use here values generated from Stacks Populations program 
### The example below uses pairwise river distance between populations. 

### P greater than 0.05 -> no evidence of ISB

setwd("path/to/wd")
getwd()

# read in genetic distance. Here Pairwise WC Fst as generated by R package HIERFSTAT
fst<-read.csv("pp_neutral_for_IBD.csv", header = FALSE, sep = ",")
m1<-as.matrix(fst)
m1
geno<-as.dist(m1)
geno

# read in geographic distance. here pairwise river km   
dist<-read.csv("final_distances.csv", header = FALSE, sep = ",")
m2<-as.matrix(dist)
m2
geo<-as.dist(m2)
geo

# run mantel test
ibd<-mantel.randtest(geo,geno,nrepet = 1000)
ibd
plot(ibd)


## Multiple regression on distance matricies in EcoDist

### P greater than 0.05 -> no evidence of ISB
### geno is response variable


MR<-MRM(geno ~ geo, nperm = 1000)
MR





